### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by Nyre221** [comment]
@Vistaus 
Thanks for the translation.

**Comment by Nyre221** [comment]
@Vistaus 
Would you like to do the Dutch translation for my new project?
https://github.com/Nyre221/Kiview

If you want to do the translation, use "Messages.sh" to generate the .pot and then put it in "/po/nl/kiview.po"

You can use lokalize to do the translation: https://apps.kde.org/lokalize/

example:
(https://invent.kde.org/games/kblocks/-/tree/master/po?ref_type=heads)

Thanks in any case.

**Comment by Vistaus** [comment]
@Nyre221 Thanks for the translation invitation! I'll start working on it ASAP! 🙂 I'm using both Poedit and Lokalize, whichever one works better when I launch it (they both can be a bit finicky at times).

**Comment by Nyre221** [comment]
@Vistaus 
>  Thanks for the translation invitation!

Thank you for helping!

>  I'll start working on it ASAP! 🙂  I'm using both Poedit and Lokalize, whichever one works better when I launch it (they both can be a bit finicky at times).

Kiview is a rewrite of QuickView in C++, and as such, it doesn't have many strings to translate and it shouldn't take long.

Thanks again.

**Pull request merged**
